# Export Terraform output variable values to a stack yaml file 
# that can be consumed by zenml stack import
resource "local_file" "stack_file" {
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the K3D MLOps stack recipe.
    zenml_version: ${var.zenml_version}
    stack_name: k3d_minimal_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      artifact_store:
        id: ${uuid()}
        flavor: s3
        name: k3d-minio-${random_string.cluster_id.result}
        configuration:
          path: "s3://${local.minio.zenml_minio_store_bucket}"
          key: "${var.minio_store_access_key}"
          secret: "${var.minio_store_secret_key}"
          client_kwargs: '{"endpoint_url":"${module.minio_server.artifact_s3_endpoint_url}", "region_name":"us-east-1"}'
      container_registry:
        id: ${uuid()}
        flavor: default
        name: k3d-${local.k3d_registry.name}-${random_string.cluster_id.result}
        configuration:
          uri: "k3d-${local.k3d_registry.name}-${random_string.cluster_id.result}.localhost:${local.k3d_registry.port}"
      orchestrator:
        id: ${uuid()}
        flavor: kubeflow
        name: k3d-kubeflow-${random_string.cluster_id.result}
        configuration:
          kubernetes_context: "k3d-${k3d_cluster.mlops_cluster.name}"
          synchronous: true
          local: true
      experiment_tracker:
        id: ${uuid()}
        flavor: mlflow
        name: k3d_mlflow_${random_string.cluster_id.result}
        configuration:
          tracking_uri: "${module.mlflow.mlflow_tracking_url}"
          tracking_username: "${var.mlflow_username}"
          tracking_password: "${var.mlflow_password}"
      model_deployer:
        id: ${uuid()}
        flavor: seldon
        name: k3d-seldon-${random_string.cluster_id.result}
        configuration:
          kubernetes_context: "k3d-${k3d_cluster.mlops_cluster.name}"
          kubernetes_namespace: "${local.seldon.workloads_namespace}"
          base_url:  "http://${module.istio.ingress_ip_address}"
          kubernetes_secret_name: "${var.seldon_secret_name}"
      secrets_manager:
        id: ${uuid()}
        flavor: local
        name: k3d-secrets-manager-${random_string.cluster_id.result}
        configuration: {}
    ADD
  filename = "./k3d_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yaml"
}